FROM fedora:40

RUN mkdir -p /usr/src/pecl-eio
WORKDIR /usr/src/pecl-eio

COPY . .

RUN dnf update -y \
    && dnf install -y gcc-14'*' php-cli php-devel php-pear make \
    && dnf clean all

RUN sh rebuild.sh

ENV NO_INTERACTION=1
CMD sh run-tests.sh

# vim: ft=dockerfile
